SRC_DIR := ./src
BIN_DIR := ./bin
OBJ_DIR := ./obj
INC_DIR := ./inc
INC_DIRS := $(addprefix -I,$(INC_DIR))

LIB_DIR := ./lib
LIB_DIRS := $(addprefix -L,$(LIB_DIR))

LIB_FLAG := 
LIB_FLAGS := $(addprefix -l,$(LIB_FLAG))

CXX := g++ 
CXXFLAGS := -g -Wall #-std=c++17
EXEC := prog
SRC := $(wildcard */*.cpp) 
OBJS := $(SRC:$(SRC_DIR)/%.cpp=$(OBJ_DIR)/%.o)

.PHONY: all

all: ${EXEC}

${EXEC} : ${OBJS}
	${CXX} ${CXXFLAGS} -o $(BIN_DIR)/$@ $^ $(INC_DIRS) $(LIB_DIRS) $(LIB_FLAGS)

$(OBJ_DIR)/%.o : $(SRC_DIR)/%.cpp
	${CXX} ${CXXFLAGS} $(INC_DIRS) -c $< -o $@ 
	#evtl. -c $^ instead of $<

run: 
	$(BIN_DIR)/$(EXEC)

clean:
	rm -f $(BIN_DIR)/* ${OBJ_DIR}/*

.PHONY: all run clean


